blog/urls.py
from django.urls import path
from . import views
from.views import PostDetailView, PostListView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('<int:pk>/', PostDetailView.as_view(), name='blog-details'),
]

personalportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('', include('user.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='port-home'),
    path('about', views.about, name='port-about'),
    path('resume', views.resume, name='port-resume')

]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.register, name='user-register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'user/login.html'), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(), name='user-logout')

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
#from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # date_posted = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class TechStack(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(default=None, blank=True, null=True)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_list_or_404
from .models import Post
from django.views.generic import DetailView, ListView

# def blog(request, *args, **kwargs):
#     posts = Post.objects.all()
#     return render(request, 'blog/blog.html', {'posts': posts})

class PostListView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'posts'
    # ordering = ['-date_posted']


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/details.html'

portfolio/views.py
from django.shortcuts import render
from .models import TechStack, Project
def home(request):
    techstacks = TechStack.objects.all()
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'techstacks': techstacks, 'projects': projects})

def about(request):
    return render(request, 'portfolio/about.html', {})

def resume(request):
    return render(request, 'portfolio/resume.html', {})

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect('user-login')
    else:
        form = UserCreationForm()
    return render(request, 'user/register.html', {'form': form})

blog/templates/blog/blog.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href='{% static "portfolio/custom.css" %}'>

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'port-home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Sumit Dadwal</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/Resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/sumitdadwal1/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/SumitDadwal12" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'port-home' %}" class="btn btn-primary">Home</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Sumit has written {{ posts.count }} blog{{ posts.count|pluralize }}</h3>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}}"> {{message}}</div>
  {% endfor %}
{% endif %}
{% for post in posts %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:blog-details' post.id %}">
      <h2>{{ post.title }}</h2>
    </a>
<!--    <h5 class="text-muted">{{ post.date|date:'M d Y'|upper }}</h5>-->
    <h4>{{ post.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

<!--truncatechars used for limitng the word count on home page article and striptags used for hiding '<b>' and other tags from literally showing up in article.-->

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h2>{{object.title}}</h2>
<p>{{object.author}} | {{post.date_posted|date:'M d, Y'}}</p>
<p>{{object.description|safe}}</p>
{% endblock content %}


<!--#we always loop over object while using class based views unless we changed it manually from views-->

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href='{% static "portfolio/custom.css" %}'>

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href='{% static "portfolio/Logo.png" %}'>

  <title>Sumit Dadwal</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'port-home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Sumit Dadwal</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/Resumesumit.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/sumitdadwal1/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/SumitDadwal12" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:blog-home' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/sumitimg.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Hi, I am Sumit! I am a Self-Taught Backend Developer specialized in Python and its various libraries.</h1>
  </div>
</div>

<h2 class="mt-5">Tech Stack:</h2>
<hr>
<div class="row">
  {% for techstack in techstacks %}
  <div class="col-lg-4 col-md-6">

    {% if techstack.url %}
    <a href="{{ techstack.url }}">
      <img src="{{ techstack.image.url }}" width="300" height="300" class="img-fluid mb-2">
    </a>
    {% else %}
      <img src="{{ techstack.image.url }}" width="300" height="300" class="img-fluid mb-2">
    {% endif %}
        <h3>{{ techstack.title }}</h3>
        <p>{{ techstack.description }}</p>

  </div>
  {% endfor %}


<div>
  <h2 class="mt-5">Projects:</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" width="400" height="400" class="img-fluid mb-2">
    </a>
    {% else %}
      <img src="{{ project.image.url }}" width="400" height="400" class="img-fluid mb-2">
    {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>
</div>

{% endblock %}

user/templates/user/login.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Don't have an Account? <a class="ml-2" href="{%url 'user-register'%}">Sign up</a>
            </small>
        </div>
    </div>
{% endblock content %}

user/templates/user/register.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}